### PR TITLE
Allow activateConsumer callback to be async

### LINKED ISSUE #24: Take "onMessage: Promise<void>" instead of "onMessage: void" for activateConsumer
Hello,

I have a question for you, here a use case : 

```
...
// define the consumer for the queue
queue.activateConsumer( async (message) => {
  let msg = message.getContent();
  if (await service.isExist(message.content.id)) {
    // other logic here
  }
}, {noAck: true});
```

I can't do something like this because activateConsumer will call my arrow function without awaiting. So it will be like "fire and forget pattern". if service.isExist fails, I will get an unhandledexception.

The solution would be : 

```// define the consumer for the queue
queue.activateConsumer( async (message) => {
  let msg = message.getContent();
  service.isExist(message.content.id).then((isExist)=> {
    if(isExist) {
      // other logic here
    }
  }).catch(doSomething);
}, {noAck: true});

```

Is there a better alternative ? It would be nice to use es6 features.

### PR DESCRIPTION
**Pull request by fan-tom**
Fixes #24, not tested, I cannot run tests, 

```
$gulp test                                                                                                                                                                                 
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/alexey/Development/js/amqp-ts/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/alexey/Development/js/amqp-ts/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/alexey/Development/js/amqp-ts/node_modules/graceful-fs/fs.js:1:37)
```

### CODE REVIEW

**Comment by abreits** [comment]
I have fixed the problem you are having (old gulp, new node version problem), you should be able to run tests now.

Can you re-submit your pull request for this version, so I can merge it?

**Comment by fan-tom** [comment]
I rebased to master and run tests, however "should process an exchange rpc" failed with  `Timeout of 1500ms exceeded`. I run that test on master and get the same result

**Comment by austin-beer** [comment]
It turns out that my PR #44 touched the same code that this PR touched but fixed a different issue. So I went ahead and included this PR's changes in my PR so that only a single PR needs to be merged. When I run "npm run test" on both master and my branch, all tests pass.

**Comment by abreits** [comment]
Sorry, read that wrong and merged this pull request, could you update your PR #44 so I can merge it?

**Comment by austin-beer** [comment]
Yes, I'll update PR #44.

**Pull request merged**
